name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build-test
      run: g++ -Wall -Wextra -Werror --coverage -o receiver-test Receiver-test.cpp DailyDataEntry.cpp StatsCalculator.cpp WriteCSV.cpp

    - name: build-main
      run: g++ -Wall -Wextra -Werror -o sender Sender.cpp && g++ -Wall -Wextra -Werror -o receiver Receiver.cpp DailyDataEntry.cpp StatsCalculator.cpp WriteCSV.cpp

    - name: static analysis
      run: cppcheck --enable=all --error-exitcode=1 -iReceiver-test.cpp . 
      
    - name: run-test
      run: ./receiver-test
    
    - name: coverage report
      run: gcov -r Receiver-test.cpp WriteCSV.cpp DailyDataEntry.cpp StatsCalculator.cpp

    - name: run
      run: ./sender|./receiver