name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
      
    - name: build
      run: g++ -Wall -Wextra -Werror --coverage -o receiver-test Receiver-test.cpp funR.cpp && g++ -Wall -Wextra -Werror --coverage -o sender-test Sender-test.cpp funS.cpp && g++ -Wall -Wextra -Werror --coverage -o receiver Receiver.cpp && g++ -Wall -Wextra -Werror --coverage -o sender Sender.cpp
      
    - name: static analysis
      run: cppcheck --enable=all --error-exitcode=1 -iReceiver-test.cpp -iSender-test.cpp . 
      
    - name: run-test
      run: ./sender-test && ./receiver-test
    
    - name: coverage report
      run: gcov -r Receiver-test.cpp funR.cpp Sender-test.cpp funS.cpp

    - name: run
      run: ./sender|./receiver